### ISSUE TITLE
Warnings and LST mismatch with ms to uvfits conversion

### ISSUE THREAD

**Issue by rlbyrne** [RadioAstronomySoftwareGroup/pyuvdata#1054] opened 2021-09-24 23:30 UTC
I am converting OVRO-LWA data files from ms to uvfits, and I am getting a series of warnings.

First, I am reading in the ms file with the command `uv.read_ms('2018-03-21-01:26:33_0004384620257280_000000.ms')`, and I get this warning:
"ITRF coordinate frame detected, although within cotter this is synonymous with J2000. Assuming J2000 coordinate frame."

Next, I am writing the data out to a uvfits file. The command `uv.write_uvfits('2018-03-21-01:26:33_0004384620257280_000000.uvfits')` fails on line 986 of `write_uvfits` with this error:
"ValueError: Required attribute _dut1 for uvfits not defined. Define or set spoof_nonessential to True to spoof this attribute."
When I add the keyword `spoof_nonessential` I get no errors or warnings.

Finally, and most concerning, when I read in the uvfits file again with the command `uv2.read_uvfits('2018-03-21-01:26:33_0004384620257280_000000.uvfits')` I get this warning:
"Telescope OVRO_MMA is not in known_telescopes.
LST values stored in this file are not self-consistent with time_array and telescope location. Consider recomputing with utils.get_lst_for_time."

**Comment by bhazelton** [comment] 2021-09-24 23:32
I've traced the "LST values stored in this file are not self-consistent with time_array and telescope location" warning to a loss of precision in the uvfits writer. This is caused by an error in how the times are written out, they should be written as two float32 arrays and comments in the code suggest that they are but in fact only a single array is being written out. This is fixed in PR #1053

**Comment by bhazelton** [comment] 2021-09-24 23:34
We should update the handling of "ITRF" in read_ms because it seems that is not just used by Cotter (it may also be used by the CASA `importfromuvfits` task as well as in these LWA files).

**Comment by bhazelton** [comment] 2021-09-24 23:36
@rlbyrne we would welcome a PR to add LWA to the known telescopes.

**Comment by bhazelton** [comment] 2021-10-04 17:48
The warning about "ITRF coordinate frame detected" was been removed with the improved MS handling in PR #995.

Adding the LWA telescope to the known telescopes was moved to its own issue, #1055.

The only remaining thing on this issue is the need to set `spoof_nonessential=True` to write uvfits. I'm going to make an issue for that and close this one.

**Closed** 2021-10-04 17:54 UTC
Labels: bug, warning, UVData
