### ISSUE TITLE
Antenna table does not reflect actual data for FHD sav conversions

### ISSUE THREAD

**Issue by nicholebarry** [RadioAstronomySoftwareGroup/pyuvdata#1059] opened 2021-09-28 04:17 UTC
Antenna table describes the hypothetical, fully-working MWA array for FHD sav->uvfits conversions. However, the actual data may have non-reporting antennas, and thus the recorded uvfits is smaller (i.e. cross-correlations for 127 antennas instead of 128 antennas). 

This may hinder measurement set conversion, or any software which takes the antenna table literally.

**Comment by bhazelton** [comment] 2021-09-28 15:12
That's by design and the uvfits antenna table is designed the same way, to contain metadata for all the antennas not just the ones with data in any given file (actually the antenna table in FHD files is basically just a copy of the input uvfits antenna table). This is very useful because then this metadata is stable across files. On UVData the details are:

- Nants_telescope gives the number of antennas that have position information (this would be all the antennas in the antenna table)
- Nants_data gives the number of antennas with data associated with them (this is counting the number of antennas that have any visibility data associated with them)
- antenna_numbers is length Nants_telescope
- antenna_names is length Nants_telescope
- antenna_positions is shape (3, Nants_telescope)
- ant_1_array and ant_2_array are length Nblts (number of baseline-times) and give the first and second antenna number for each baseline-time. Counting the unique numbers that appear in the union of these arrays is how we derive Nants_data.

**Comment by bhazelton** [comment] 2021-09-28 15:16
I just read your comment more carefully and saw the concern about measurement set conversion. We are actually just about to merge in a measurement set writer. We do have to worry about and handle this issue there but there are semi-standard ways to handle that without changing the antenna numbers (essentially having extra rows in some tables).

If you'd like to play with the ms_writer now, it's in the `write_ms` branch, otherwise we hope to have a new version out with it included in a week or two.

**Comment by bhazelton** [comment] 2021-10-04 17:43
@nicholebarry There's now an MS writer in pyuvdata (as of version 2.2.2). Does that alleviate your concern about this or do you think we need to add some documentation somewhere?

**Comment by bhazelton** [comment] 2023-02-27 01:34
@nicholebarry checking back in on this, should it still be open?

**Comment by bhazelton** [comment] 2023-07-13 18:45
@nicholebarry I'm going to close this because I think it's properly handled in our MS writer. Feel free to re-open if I'm missing something.

**Closed by bhazelton** 2023-07-13 18:45 UTC
Labels: UVData
